name: manage-azure-policy-dbfebc69
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policy/policies/Cloud_Default_Tags_Audit_Policy_25b87cb1-ec06-43c1-98eb-82ad596b9bf7/**'
#      - .github/workflows/manage-azure-policy-dbfebc69.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_dbfebc69}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policy/policies/Cloud_Default_Tags_Audit_Policy_25b87cb1-ec06-43c1-98eb-82ad596b9bf7/**
